### YamlMime:ManagedReference
items:
- uid: CodeJam.PerfTests.Configs
  commentId: N:CodeJam.PerfTests.Configs
  id: CodeJam.PerfTests.Configs
  children:
  - CodeJam.PerfTests.Configs.CompetitionAdjustmentMode
  - CodeJam.PerfTests.Configs.CompetitionAnnotationMode
  - CodeJam.PerfTests.Configs.CompetitionCheckMode
  - CodeJam.PerfTests.Configs.CompetitionConfigExtensions
  - CodeJam.PerfTests.Configs.CompetitionFeatures
  - CodeJam.PerfTests.Configs.CompetitionIgnoreAllocationsAttribute
  - CodeJam.PerfTests.Configs.CompetitionMaximumRerunsAttribute
  - CodeJam.PerfTests.Configs.CompetitionMeasureAllAttribute
  - CodeJam.PerfTests.Configs.CompetitionMeasureAllocationsAttribute
  - CodeJam.PerfTests.Configs.CompetitionNoRelativeTimeAttribute
  - CodeJam.PerfTests.Configs.CompetitionOptions
  - CodeJam.PerfTests.Configs.CompetitionRunMode
  - CodeJam.PerfTests.Configs.ConcurrentRunBehavior
  - CodeJam.PerfTests.Configs.ICompetitionConfig
  - CodeJam.PerfTests.Configs.ICompetitionConfigSource
  - CodeJam.PerfTests.Configs.ManualCompetitionConfig
  - CodeJam.PerfTests.Configs.ReadOnlyCompetitionConfig
  langs:
  - csharp
  - vb
  name: CodeJam.PerfTests.Configs
  nameWithType: CodeJam.PerfTests.Configs
  fullName: CodeJam.PerfTests.Configs
  type: Namespace
  assemblies:
  - CodeJam.PerfTests
references:
- uid: CodeJam.PerfTests.Configs.CompetitionAnnotationMode
  commentId: T:CodeJam.PerfTests.Configs.CompetitionAnnotationMode
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionAnnotationMode
  nameWithType: CompetitionAnnotationMode
  fullName: CodeJam.PerfTests.Configs.CompetitionAnnotationMode
- uid: CodeJam.PerfTests.Configs.CompetitionAdjustmentMode
  commentId: T:CodeJam.PerfTests.Configs.CompetitionAdjustmentMode
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionAdjustmentMode
  nameWithType: CompetitionAdjustmentMode
  fullName: CodeJam.PerfTests.Configs.CompetitionAdjustmentMode
- uid: CodeJam.PerfTests.Configs.CompetitionCheckMode
  commentId: T:CodeJam.PerfTests.Configs.CompetitionCheckMode
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionCheckMode
  nameWithType: CompetitionCheckMode
  fullName: CodeJam.PerfTests.Configs.CompetitionCheckMode
- uid: CodeJam.PerfTests.Configs.CompetitionRunMode
  commentId: T:CodeJam.PerfTests.Configs.CompetitionRunMode
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionRunMode
  nameWithType: CompetitionRunMode
  fullName: CodeJam.PerfTests.Configs.CompetitionRunMode
- uid: CodeJam.PerfTests.Configs.CompetitionOptions
  commentId: T:CodeJam.PerfTests.Configs.CompetitionOptions
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionOptions
  nameWithType: CompetitionOptions
  fullName: CodeJam.PerfTests.Configs.CompetitionOptions
- uid: CodeJam.PerfTests.Configs.CompetitionMeasureAllAttribute
  commentId: T:CodeJam.PerfTests.Configs.CompetitionMeasureAllAttribute
  isExternal: false
  name: CompetitionMeasureAllAttribute
  nameWithType: CompetitionMeasureAllAttribute
  fullName: CodeJam.PerfTests.Configs.CompetitionMeasureAllAttribute
- uid: CodeJam.PerfTests.Configs.CompetitionNoRelativeTimeAttribute
  commentId: T:CodeJam.PerfTests.Configs.CompetitionNoRelativeTimeAttribute
  isExternal: false
  name: CompetitionNoRelativeTimeAttribute
  nameWithType: CompetitionNoRelativeTimeAttribute
  fullName: CodeJam.PerfTests.Configs.CompetitionNoRelativeTimeAttribute
- uid: CodeJam.PerfTests.Configs.CompetitionMeasureAllocationsAttribute
  commentId: T:CodeJam.PerfTests.Configs.CompetitionMeasureAllocationsAttribute
  isExternal: false
  name: CompetitionMeasureAllocationsAttribute
  nameWithType: CompetitionMeasureAllocationsAttribute
  fullName: CodeJam.PerfTests.Configs.CompetitionMeasureAllocationsAttribute
- uid: CodeJam.PerfTests.Configs.CompetitionIgnoreAllocationsAttribute
  commentId: T:CodeJam.PerfTests.Configs.CompetitionIgnoreAllocationsAttribute
  isExternal: false
  name: CompetitionIgnoreAllocationsAttribute
  nameWithType: CompetitionIgnoreAllocationsAttribute
  fullName: CodeJam.PerfTests.Configs.CompetitionIgnoreAllocationsAttribute
- uid: CodeJam.PerfTests.Configs.ConcurrentRunBehavior
  commentId: T:CodeJam.PerfTests.Configs.ConcurrentRunBehavior
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: ConcurrentRunBehavior
  nameWithType: ConcurrentRunBehavior
  fullName: CodeJam.PerfTests.Configs.ConcurrentRunBehavior
- uid: CodeJam.PerfTests.Configs.CompetitionConfigExtensions
  commentId: T:CodeJam.PerfTests.Configs.CompetitionConfigExtensions
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionConfigExtensions
  nameWithType: CompetitionConfigExtensions
  fullName: CodeJam.PerfTests.Configs.CompetitionConfigExtensions
- uid: CodeJam.PerfTests.Configs.ICompetitionConfigSource
  commentId: T:CodeJam.PerfTests.Configs.ICompetitionConfigSource
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: ICompetitionConfigSource
  nameWithType: ICompetitionConfigSource
  fullName: CodeJam.PerfTests.Configs.ICompetitionConfigSource
- uid: CodeJam.PerfTests.Configs.CompetitionMaximumRerunsAttribute
  commentId: T:CodeJam.PerfTests.Configs.CompetitionMaximumRerunsAttribute
  isExternal: false
  name: CompetitionMaximumRerunsAttribute
  nameWithType: CompetitionMaximumRerunsAttribute
  fullName: CodeJam.PerfTests.Configs.CompetitionMaximumRerunsAttribute
- uid: CodeJam.PerfTests.Configs.ICompetitionConfig
  commentId: T:CodeJam.PerfTests.Configs.ICompetitionConfig
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: ICompetitionConfig
  nameWithType: ICompetitionConfig
  fullName: CodeJam.PerfTests.Configs.ICompetitionConfig
- uid: CodeJam.PerfTests.Configs.ReadOnlyCompetitionConfig
  commentId: T:CodeJam.PerfTests.Configs.ReadOnlyCompetitionConfig
  isExternal: false
  name: ReadOnlyCompetitionConfig
  nameWithType: ReadOnlyCompetitionConfig
  fullName: CodeJam.PerfTests.Configs.ReadOnlyCompetitionConfig
- uid: CodeJam.PerfTests.Configs.ManualCompetitionConfig
  commentId: T:CodeJam.PerfTests.Configs.ManualCompetitionConfig
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: ManualCompetitionConfig
  nameWithType: ManualCompetitionConfig
  fullName: CodeJam.PerfTests.Configs.ManualCompetitionConfig
- uid: CodeJam.PerfTests.Configs.CompetitionFeatures
  commentId: T:CodeJam.PerfTests.Configs.CompetitionFeatures
  parent: CodeJam.PerfTests.Configs
  isExternal: false
  name: CompetitionFeatures
  nameWithType: CompetitionFeatures
  fullName: CodeJam.PerfTests.Configs.CompetitionFeatures
- uid: CodeJam.PerfTests.Configs
  commentId: N:CodeJam.PerfTests.Configs
  isExternal: false
  name: CodeJam.PerfTests.Configs
  nameWithType: CodeJam.PerfTests.Configs
  fullName: CodeJam.PerfTests.Configs
